services:
  postgres:
    image: postgres:15-alpine
    container_name: financa-pessoal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: financeiro_db
      POSTGRES_USER: financeiro_user
      POSTGRES_PASSWORD: financeiro_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db:/docker-entrypoint-initdb.d
    networks:
      - financa-network

  pgladmin:
    image: dpage/pgladmin4:latest
    container_name: financa-pessoal-pgadmin
    restart: unless-stopped
    environment:
      PGLADMIN_DEFAULT_EMAIL: admin@financeiro.com
      PGLADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - financa-network

  redis:
    image: redis:7-alpine
    container_name: financa-pessoal-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - financa-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  financa-network:
    driver: bridge
