# Configuração Nixpacks para Railway
[phases.setup]
nixPkgs = ["curl", "jdk21"]

[phases.build]
cmds = ["./gradlew clean build -x test --no-daemon"]

[phases.deploy]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar build/libs/*.jar"

[variables]
JAVA_OPTS = "-Xmx512m -Xms256m -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"