# Configuração Nixpacks para Railway
[phases.setup]
nixPkgs = ["curl"]

[phases.build]
cmds = ["./gradlew clean build -x test --no-daemon"]

[phases.deploy]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar build/libs/financa-pessoal.jar"

[variables]
JAVA_OPTS = "-Xmx512m -Xms256m"