spring:
  application:
    name: financa-pessoal

  datasource:
    url: jdbc:postgresql://localhost:5432/financeiro
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false # Desativa exibição de SQL no console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": false # Desativa formatação de SQL
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true

app:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:5173,http://localhost:4200"
  swagger:
    enabled: true

security:
  jwt:
    secret: ${JWT_SECRET:dev-secret-key-for-local-development-only}
    expiration-time: ${JWT_EXPIRATION:86400000}

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}

logging:
  level:
    "[com.financeiro]": INFO # INFO ao invés de DEBUG (menos verboso)
    "[org.springframework.security]": INFO # INFO ao invés de DEBUG
    "[org.hibernate.SQL]": INFO # INFO ao invés de DEBUG (não mostra queries)
    "[org.hibernate.type.descriptor.sql.BasicBinder]": INFO # INFO ao invés de TRACE
