# Configurações para ambiente de desenvolvimento
spring:
  # Banco H2 em memória para desenvolvimento
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # Configurações JPA para desenvolvimento
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Console H2 para desenvolvimento
  h2:
    console:
      enabled: true
      path: /h2-console

# Configurações de logging para desenvolvimento
logging:
  level:
    com.financeiro: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

# Configurações da aplicação
app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
      - http://localhost:8080
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers: "*"
    exposed-headers:
      - Authorization
      - Content-Type
    max-age: 3600

# Configurações do Swagger para desenvolvimento
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Configurações de monitoramento
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
