# Configurações para produção
spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}

# JWT
security:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
