spring:
  application:
    name: financa-pessoal

  datasource:
    url: jdbc:h2:mem:financeiro_db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: false

server:
  port: 8080

logging:
  level:
    "[com.financeiro]": DEBUG
